services:
  backend:
    build:
      context: ./backend
    container_name: svtech-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
    container_name: svtech-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
